"use client";
import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { UserProvider } from "@/components/UserContext";
export default function Layout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body>
          <Navbar />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
// import "./globals.css";
// import { Inter } from "next/font/google";
// import Navbar from "./../components/Navbar/Navbar";
// import { useEffect, useState } from "react";
// import { useRouter } from "next/navigation";
// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Fast sell",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   const router = useRouter();
//   const [user, setUser] = useState({ value: null });
//   const [key, setKey] = useState(0);
//   useEffect(() => {
//     const token = localStorage.getItem("token");
//     if (token) {
//       setUser({ value: token });
//       setKey(Math.random());
//     }
//   }, [router.query]);
//   console.log(router.pathname);
//   const logout = () => {
//     localStorage.removeItem("token");
//     setUser({ value: null });
//   };
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <Navbar user={user} key={key} logout={logout} />
//         {children}
//       </body>
//     </html>
//   );
// }
